// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uknpfhmukdswvbcuuumj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbnBmaG11a2Rzd3ZiY3V1dW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTI3MjQsImV4cCI6MjA2NjgyODcyNH0.Oc1GGTYosHsbZVJTBLN3jiZijKV0q1y7qtkh7pJg94c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});